### ISSUE TITLE
Translate Python to C++: zeroes function in starter code causes segmentation fault

### ISSUE THREAD

**Issue by carsten-grimm** [udacity/isdc_issues_tracker#71] opened 2017-11-04 16:22 UTC
There seems to be something wrong with the zeroes function in the starter code for the project where we are translating from python to c++.

This is the function that causes a segfault:
```
vector < vector <float> > zeros(int height, int width) {
	int i, j;
	vector < vector <float> > newGrid;
	vector <float> newRow;

	for (i=0; i<height; i++) {
		newRow.clear();
		for (j=0; j<width; j++) {
			newRow.push_back(0.0);
		}
		newGrid.push_back(newRow);
	}
	return newGrid;
}
```

After replacing this function with 
```
vector < vector <float> > zeros(int height, int width) {

	vector < vector <float> > newGrid;
	newGrid.assign(height, vector<float>(width, 0.0));

	return newGrid;
}
``` 
everything works. 

The segmentation fault occurs on Linux Debian 9 with both g++ 6.3.0 and clang++ 3.8. The fix also works for both g++ and clang++.

**Comment by carsten-grimm** [comment] 2017-11-04 16:22
P.S.: The offending function is at the bottom of the file helpers.cpp

**Comment by carsten-grimm** [comment] 2017-11-04 16:38
This replacement is a bit shorter and works, too: 
```
vector < vector <float> > zeros(int height, int width) {
    return vector < vector <float> >(height, vector<float>(width, 0.0));
}
```

**Comment by AndyAtUdacity** [comment] 2018-01-24 18:26
I'm not able to reproduce and I believe this was fixed earlier. I'm marking as closed.

**Closed by AndyAtUdacity** 2018-01-24 18:26 UTC
