### ISSUE TITLE
Can`t access C++ link learning resource

### ISSUE THREAD

**Issue by warlockz** [udacity/isdc_issues_tracker#5] opened 2017-10-10 01:02 UTC
https://www.udacity.com/course/c-for-programmers--ud210

**Comment by warlockz** [comment] 2017-10-10 01:03
Error :
404
Sorry, we can't seem to find 
the page you are looking for.

UDACITY HOME

**Comment by minrafa** [comment] 2017-10-11 08:35
I have this problem too. Wrote to support team but haven't got any response yet.

**Comment by silentwater** [comment] 2017-10-13 07:23
Duplicate of Defect #1

**Comment by AndyAtUdacity** [comment] 2017-10-19 20:29
Thanks for pointing this out. I'm closing this issue since it's a duplicate of #1

**Closed by AndyAtUdacity** 2017-10-19 20:29 UTC
