### ISSUE TITLE
Lesson 2: Shortest path error when submitting

### ISSUE THREAD

**Issue by viadanna** [udacity/isdc_issues_tracker#149] opened 2017-12-06 20:53 UTC
Lesson: https://classroom.udacity.com/nanodegrees/nd113/parts/ad7e52df-3387-4252-b4bd-9c40aecb8093/modules/14fc0233-3169-4ca5-8255-ed921d2d973a/lessons/56980e75-08e4-4b3c-ba7f-58f10e963980/concepts/6146c6bc-68c8-498b-b6bd-8c16bee2886b

Submitting return "L" if L1 + L2 - L3 - L4 > 0 else "R" results in error:
{u'vm_time': 0.12108492851257324, u'stdout': u'', u'vm_creation_time': 6.389617919921875e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n File "vm_main3.py", line 47, in \n import main\n File "/tmp/vmuser_obkfjzgbom/main.py", line 2, in \n import aiMain\n File "/tmp/vmuser_obkfjzgbom/aiMain.py", line 22\n \uff03\u4e0b\u9762\u7684\u4ee3\u7801\u7c7b\u4f3c\u4e8e\u4f18\u8fbe\u5b66\u57ce\n ^\nSyntaxError: invalid character in identifier\n', u'exec_server_time': 0.12420988082885742, u'exec_status': u'error'}

Test run works though.

**Comment by xperroni** [comment] 2017-12-10 11:37
This is a duplicate of issue 136, "Challenge: Shortest Path - submission error".

**Comment by xperroni** [comment] 2017-12-10 11:38
URL to original issue:
https://waffle.io/udacity/isdc_issues_tracker/cards/5a2450fa29c4d2001d4a0f07

**Comment by viadanna** [comment] 2017-12-10 12:46
Missed that one, closing this.

**Comment by andrewsdc** [comment] 2018-01-04 19:59
Hey, thank you guys for being on top of this. We're going through the Waffleboard tasks and will get to #136 hopefully soon. I'll close this one and leave #136 open.

**Closed** 2018-01-04 19:59 UTC
